### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by ks2022ml** [biomedbigdata/BiCoN#13]
Hi

How can i pass in the metadata for the patient/samples for the biclustering?

Thank you.

**Comment by mlist** [comment]
Hi @ks2022ml, bicon is an unsupervised approach and thus does not necessarily need any metadata. Are you trying to run the web interface or the python package? For the latter check out the readme:

"If you have a patient's phenotype you would like to use for comparison, please make sure that patients IDs are exactly (!) matching the IDs that were used as an input. The IDs should be represented as a list of two lists, e.g.:"

```
true_classes = [['GSM748056', 'GSM748059',..], ['GSM748278', 'GSM748279', 'GSM1465989']]
results.show_clustermap(GE, G, output = "results/clustermap.png", true_labels = true_classes)
```

**Comment by ks2022ml** [comment]
Thank you for the clarification!

I am trying to run BiCoN but the model.run_search has been running for a few hours without completing even though it says that "Full convergence achieved". What could be the cause?

```Runtime statistics:
###############################################################
the joint graph has 1817 nodes
probability update takes 2.338
Iteration # 1
One ant work takes 21.95 with 16 processes
best round score: 0.084
average score: 0.084
Count small = 0
One full iteration takes 25.18 with 16 processes
Full convergence achieved
best  score: 0.08422514257011385```

**Comment by Laolga** [comment]
Hi @ks2022ml! Sorry for the inconvenience, it is very strange behavior indeed. Unfortunately, I can not tell if something looks odd just from the log. Would it be possible for you to share your input data with me? If so please email me personally at olazareva1993@gmail.com I would be happy to help and your data will be treated with confidentiality
