### ISSUE TITLE
BiCON web analysis error 

### ISSUE THREAD

**Issue by kabdilleh** [biomedbigdata/BiCoN#14]
Hello, 
I was attempting to run BiCON-Web analysis using my own gene expression & PPI datasets. 
I get the following non-descriptive error message:
An unknown error has occured.
Please contact the administrator of this site and provide the settings you used in this run.
Please also provide this task-id: a5078030-3a66-466e-a47d-861bf4bb3415

I also get an error when running even the sample lung cancer data. Is the web interface no longer working? I appreciate any help with this. Thank you!

**Comment by kevihiiin** [comment]
Hi kabdilleh,
Thank you for raising the issue and also testing it on the demo lung cancer data!

We observed the same problem you have described and fixed it in [release v1.2.1](https://github.com/biomedbigdata/BiCoN-web/releases/tag/v1.2.1) of the [BiCoN-web](https://github.com/biomedbigdata/BiCoN-web).
The deployed live version is still on an older version.

@mlist could you help us deploy the latest version to close this issue?

Best,
Kevin

**Comment by mlist** [comment]
I deployed the fix and it was working for me now. Please close the issue if it works for you, too @kabdilleh .

**Comment by kabdilleh** [comment]
Hi @kevihiiin and @mlist, thank you very much! I was able to confirm that the issue is resolved. I can close it now. Thank you again!
