### ISSUE TITLE
gseapy dependency now requires Rust to be installed

### ISSUE THREAD

**Issue by james-skelton** [biomedbigdata/BiCoN#15]
Since release v0.12.0 (13th Aug 2022), `gseapy` now requires the Rust programming language as a dependency. It may be worth either:

- Adding this to the documentation so that users know to install Rust on their system.
- Setting a version of `gseapy` that is a earlier than 0.12.0 in the dependencies

It may also be possible to set up a `conda` package to avoid the manual Rust installation (as this manual step isn't mentioned in the `gseapy` installation documentation).

**Comment by Laolga** [comment]
Thanks for pointing that out. The dependency is fixed now.
