### ISSUE TITLE
Import Error - Data preprocessing

### ISSUE THREAD

**Issue by ShokofehVS** [biomedbigdata/BiCoN#16]
Hello!

I want to do some experiments by BiCoN over my data set. While following instructions on example section, it raised an error: **ImportError: cannot import name 'data_preprocessing' from partially initialized module 'bicon' (most likely due to a circular import)**

I appreciate your help.

**Comment by JohannesKersting** [comment]
Hi!
Thanks for reporting that

I could not reproduce your issue.
Which way did you install bicon?
Using
`pip install bicon`
or
`git clone https://github.com/biomedbigdata/BiCoN`
`python setup.py install`
?

Did the installation complete successfully?

**Comment by ShokofehVS** [comment]
What I did successfully first was working via my terminal and installing the package by `pip install bicon`. However, cloning the project and executing example step by step gives out the corresponding error. 

A follow-up question: I would like to ask whether we can run the BiCoN according to the steps written on repo over different kind of data sets like Intrusion Detection Systems. 

Thank you for your reply and for such a comprehensive solution for gene expression analysis.

**Comment by mlist** [comment]
It sounds like you have an unclean installation after running both pip and the github installation. You can run BiCoN on any kind of data set but we have only tested it thoroughly on gene expression data so we can not give you much advise on fundamentally different types of data or networks. Would be cool if it helps you though!

**Comment by ShokofehVS** [comment]
Thank you!
