### ISSUE TITLE
"Probability update takes" stuck on 0.0 and not producing output

### ISSUE THREAD

**Issue by damonot** [biomedbigdata/BiCoN#5]
```
Run time statistics:
###############################################################
the joint graph has 23 nodes
probability update takes 0.0
```

No additional output after ~30 minutes for a small dataset compared to the sample shown in the BiCon README.md

reference files:
[](https://drive.google.com/file/d/1C98kLQGv9teMT_eQ__T61I5IlY1gxkr4/view?usp=sharing)

**Comment by kevihiiin** [comment]
@damonot thank you for raising this issue. 
As far as I understood the example in the README does work on your machine and therefore the installation should have been successful.

We would like to reproduce and fix this issue. If possible, could you please share the information with us:
+ Operating system
+ Python version
+ `pip freeze` output (installed python packages) 
+ Used parameters (or script of how BiCoN is called)
+ Used data set

**Comment by damonot** [comment]
Hi Kevin,Thanks for getting back so quickly. I’ve attached the script, pip freeze, and dataset in a zip file.OS: Windows 10 Pro. Version 10.0.18362 Build 18362Python 3.7.6  From: Kevin YuanSent: Monday, July 20, 2020 4:20 PMTo: biomedbigdata/BiCoNCc: Damon; MentionSubject: Re: [biomedbigdata/BiCoN] "Probability update takes" stuck on 0.0 and not producing output (#5) @damonot thank you for raising this issue.As far as I understood the example in the README does work on your machine and therefore the installation should have been successful.We would like to reproduce and fix this issue. If possible, could you please share the information with us:Operating systemPython versionpip freeze output (installed python packages)Used parameters (or script of how BiCoN is called)Used data set—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mlist** [comment]
Hi @damonot We appreciate that you take the time to evaluate BiCoN. Unfortunately we do not see any attachment in your last message. Could you please attach it again?

**Comment by damonot** [comment]
- OS: Windows 10 Pro. Version 10.0.18362 Build 18362
- Python 3.7.6
Sorry, not sure why it won't attach...here's a link to the files instead: [files](https://drive.google.com/file/d/1uzXeL2Ay6tGixUHrYNYc599MMKkYOaVs/view?usp=sharing)

**Comment by Laolga** [comment]
Hi @damonot ! Thank you again for raising the issue. It happened due to the fact that the algorithm was calibrated for larger sizes of data. We updated our approach such that it does not freeze under any circumstances and also tunes hyperparameters accordingly even for small datasets. 

You can update either through PyPI or using github pull request.

**Comment by damonot** [comment]
Interesting, thank you!
