### ISSUE TITLE
Possibility of logging output (rather than printing)

### ISSUE THREAD

**Issue by james-skelton** [biomedbigdata/BiCoN#8]
Not a bug, but a feature request -- it would be nice if the verbose output could be optionally logged to a file (instead of, or in addition to, printing). I'm currently exposing BiCoN as a service in an API, and capturing runtime logs would be useful for API users to follow what happened with their data.

**Comment by Laolga** [comment]
Hi James!
Thanks a lot for your feedback. The package was updated and now you can set verbose = True (or False) depending on whether you want to see the output in the console and logging = True (or False) to save logs to a file bicon_logging.txt
Please feel free to reach out if you have any other feedback or suggestions.
